### ISSUE TITLE
Unable to install alchemy in spree (3.4.4) project

### ISSUE THREAD

**Issue by amitbishtZT** [AlchemyCMS/alchemy_spree#31] opened 2018-05-02 06:51 UTC
Hi,
I am unable to install alchemy (4.0-stable) in existing spree (3.4.4) with rails (5.1.6) solution.
getting below error-

> Bundler could not find compatible versions for gem "cancancan":
>   In snapshot (Gemfile.lock):
>     cancancan (= 2.2.0)
> 
>   In Gemfile:
>     alchemy_cms was resolved to 4.0.1, which depends on
>       cancancan (~> 1.9)
> 
>     spree (~> 3.4.4) was resolved to 3.4.5, which depends on
>       spree_core (= 3.4.5) was resolved to 3.4.5, which depends on
>         cancancan (~> 2.0)

**Comment by tvdeyen** [comment] 2018-05-02 07:31
Duplicate of https://github.com/AlchemyCMS/alchemy_cms/issues/1417

**Closed by tvdeyen** 2018-05-02 07:31 UTC
